# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  orderserviceapi:
    image: orderserviceapi
    build:
      context: .
      dockerfile: src/Services/OrderService/OrderService.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5086:5086
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      
